@startuml
' Цвета
!define BLUE #ADD8E6
!define LIGHT_BLUE #B0E0E6
!define GREEN #90EE90
!define ORANGE #FFA500
!define PURPLE #DDA0DD

component PluginLoader{
' Компоненты внутри PluginLoader
component "ModelStorage" BLUE
component "MetricsModel" LIGHT_BLUE
component "PingNodeModel" LIGHT_BLUE
component "PingNodePlugin" PURPLE
component "PrometheusExporterPlugin" PURPLE
}

component "Prometheus" GREEN
component "Grafana" ORANGE

' Взаимосвязи
PingNodeModel --> ModelStorage
PrometheusExporterPlugin <-- MetricsModel : Upload metrics
PingNodePlugin --> PingNodeModel : Export interface for plugins

MetricsModel --> ModelStorage
PingNodePlugin --> MetricsModel : metrics
PluginLoader --> Prometheus : exports metrics
Prometheus --> Grafana : provides metrics

@enduml
